name: CD@eslint-config-strict-check

on:
  push:
    branches:
      - main

jobs:
  publish:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/eslint-config-strict-check

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ./.node-version

      - name: Can publish
        run : npx can-npm-publish --verbose
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Install dependencies
        run: yarn

      - name: Run lint
        run: yarn lint

      - name: Run spell-check
        run: yarn spell-check

      - name: Run type-check
        run: yarn type-check

      - name: Run test
        run: yarn test

      - name: Build
        run: yarn build

      - name: Check the codes
        run: yarn dry-run

      - name: Publish
        run: yarn publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
