name: CI@eslint-config-strict-check

on:
  pull_request:
    branches:
      - develop
      - main
      - feature/**
    paths:
      - 'packages/eslint-config-strict-check/**'
      - 'yarn.lock'
      - 'configs/**'

jobs:
  lint:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/eslint-config-strict-check

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ./.node-version

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Check the codes
        run: yarn lint

  dry-run:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/eslint-config-strict-check

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ./.node-version

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Check the codes
        run: yarn dry-run

  spell-check:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/eslint-config-strict-check

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ./.node-version

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Check the codes
        run: yarn spell-check

  type-check:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/eslint-config-strict-check

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ./.node-version

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Check the codes
        run: yarn type-check

  test:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/eslint-config-strict-check

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ./.node-version

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Check the codes
        run: yarn test
