name: CI@eslint-config-strict-check

on:
  pull_request:
    branches:
      - develop
      - feature/**
      - main
    paths:
      - '.github/workflows/ci-eslint-config-strict-check.yml'
      - 'configs/**'
      - 'packages/eslint-config-strict-check/**'
      - 'yarn.lock'

jobs:
  check:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/eslint-config-strict-check

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ./.node-version

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run lint
        run: yarn lint

      - name: Run dry-run
        run: yarn dry-run

      - name: Run spell-check
        run: yarn spell-check

      - name: Run type-check
        run: yarn type-check

      - name: Run test
        run: yarn test
