name: CI@root

on:
  pull_request:
    branches:
      - develop
      - feature/**
      - main
    paths-ignore:
      - 'packages/**'

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ./.node-version

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run lint
        run: yarn lint
